x = [1, 2, 3]
y = 1

try:
  print(x + y)
except Exception as e:
  print(f"Erro: {e}")
finally:
  print("Tente novamente")


#print("Continuando o projeto")